USE books_genres_db;

DELETE FROM ratings
WHERE id NOT IN (SELECT id FROM users)
OR ISBN NOT IN (SELECT ISBN FROM books);


ALTER TABLE ratings
ADD CONSTRAINT fk_ratings_users
FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE;


ALTER TABLE ratings
ADD CONSTRAINT fk_ratings_books
FOREIGN KEY (ISBN) REFERENCES books(ISBN) ON DELETE CASCADE;